package com.gscape.sdp.galacticescape.Display.ActualGame;

public enum SimulationStateEnum {
    SIMULATION_STOPPED,
    SIMULATION_INITIALIZING,
    SIMULATION_RUNNING,
    SIMULATION_BACKGROUND_STOPPED,
    SIMULATION_BACKGROUND_RUNNING,
    SIMULATION_BACKGROUND_FINISHED,
    SIMULATION_BACKGROUND_ADDING,
    SIMULATION_BACKGROUND_DELETING,
    SIMULATION_DISPLAY_STOPPED,
    SIMULATION_DISPLAY_RUNNING,
    SIMULATION_DISPLAY_FINISHED,
    SIMULATION_DISPLAY_ADDING,
    SIMULATION_DISPLAY_DELETING
}
